wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.21.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1668979001
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 75
      - 77
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 75
      - 77
      3:
      - 24
      4: 3.8.10
      5: 0.12.21
      6: 4.21.0
      8:
      - 5
